### ISSUE TITLE
A# and C# in Assemblies.txt 

### ISSUE THREAD

**Issue by wzhang42** [XiaoTaoWang/NeoLoopFinder#10]
Hi, Xiaotao,
In your K562.assemblies.txt, there are two kinds of complex SV as A0,A1, A2,A3 vs C0,C1,C2,C3,C4. In my generated assemblies.txt, only one kind of complex SV as C0,C1...C31.  What's the meaning of of A# vs C# ?  What's my only-one-kind assemblies as C# means?  Whether my assemblies.txt can not get any neoloop? 
Thank you so much

**Comment by XiaoTaoWang** [comment]
Hi, C# represents assemblies of a simple SV, while A# represents assemblies of a complex SV (composed of at least 3 chromatin fragments or at least 2 simple SVs).

Yes, according to my experience, most Neo-loops are from simple SVs, just go ahead to run neoloop-caller on your assemblies.txt.

**Comment by wzhang42** [comment]
Many thanks you for your explanation. My generated neoloop list report 0. The HiC data(.cool file) is at the resolution of 5K. Whether it's the HiC resolution issues? Additionally, what's relationship between the HiC data resolution with segment-cnv' parameter --binsize?

**Comment by XiaoTaoWang** [comment]
1. resolution might be the issue if the sequencing depth of your Hi-C matrix is relatively low, one suggestion is trying to detect loops at 10kb or 25kb.
2. when you run "segment-cnv", the "--binsize" parameter should be the same as the Hi-C matrix resolution when you run "calculate-cnv"
