### ISSUE TITLE
What is the strength of the neoloops? 

### ISSUE THREAD

**Issue by joreynajr** [XiaoTaoWang/NeoLoopFinder#12]
I ran NeoLoopFinder on some data and got the following neoloops, however I can't find any sort of value indicate the strength/confidence we have in this loop. Can NeoLoopFinder provide such a value? Maybe some value from the Peakachu prediction algorithm? 
![image](https://user-images.githubusercontent.com/14253227/127379818-fd3ea289-ced5-4117-91eb-1a7f8cab1ce5.png)

**Comment by XiaoTaoWang** [comment]
Hi, thanks for the feedback, I might add this function to the next major version. For now, you need to manually tune the probability threshold via the "--prob" to obtain loops of different strength.

**Comment by joreynajr** [comment]
Thanks for the info! I'll try out the "--prob" for now.
