### ISSUE TITLE
problem in converting hic to cool inorder to run neoloop

### ISSUE THREAD

**Issue by zhangli271828** [XiaoTaoWang/NeoLoopFinder#15]
I am trying to run your neoloop code. I used hic2cool to make mcool from JUICER output file in hic format.
 
I used your code (https://raw.githubusercontent.com/XiaoTaoWang/NeoLoopFinder/master/scripts/add_prefix_to_cool.py)
to add prefix to mcool file, which gave me the following error message:
 
Traceback (most recent call last):
  File "/usr/local/python/3.8.6/lib/python3.8/site-packages/cooler/api.py", line 95, in _refresh
    _ct = chroms(grp)
  File "/usr/local/python/3.8.6/lib/python3.8/site-packages/cooler/api.py", line 448, in chroms
    .append(pd.Index(h5["chroms"].keys()))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python/3.8.6/lib/python3.8/site-packages/h5py/_hl/group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'chroms' doesn't exist)"
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "add_prefix.py", line 7, in <module>
    clr = cooler.Cooler(in_cool)
  File "/usr/local/python/3.8.6/lib/python3.8/site-packages/cooler/api.py", line 89, in __init__
    self._refresh()
  File "/usr/local/python/3.8.6/lib/python3.8/site-packages/cooler/api.py", line 110, in _refresh
    raise KeyError(err_msg)
KeyError: "No cooler found at: inter.mcool. Coolers found in ['/resolutions/1000', '/resolutions/5000', '/resolutions/10000', '/resolutions/25000', '/resolutions/50000', '/resolutions/100000', '/resolutions/250000', '/resolutions/500000', '/resolutions/1000000', '/resolutions/2500000']. Use '::' to specify a group path"

**Comment by XiaoTaoWang** [comment]
Hi, the mcool format is a different format from .cool. A .mcool file always contains multiple cool URI at different resolutions. In your case, a valid cool URI is inter.mcool::resolutions/5000, inter.mcool::resolutions/10000, or inter.mcool::resolutions/25000.

**Comment by zhangli271828** [comment]
I am not family with how to handle mcool and cool files. How do I extract a specific cool file from a mcool file?

**Comment by XiaoTaoWang** [comment]
you don't need to extract cool from mcool, just use "-H inter.mcool::resolutions/10000" (or similarly "-H inter.mcool::resolutions/25000") when you run any command of the NeoLoopFinder toolkit

**Comment by Spartanzhao** [comment]
When I trying to install the package as the instruction ,I got erro like this :
bogon:result yuezhao$ conda install -c r r=3.5.1 rpy2=2.9.4 r-mgcv=1_23 -y 
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package r conflicts for:
r-mgcv=1.8_23 -> r-nlme[version='>=3.1'] -> r[version='3.2.0.*|3.2.1.*|3.2.2.*']
rpy2=2.9.4 -> r-rsqlite -> r[version='3.1.3.*|3.2.0.*|3.2.1.*|3.2.2.*']
r=3.5.1

Package libgfortran4 conflicts for:
rpy2=2.9.4 -> r-base[version='>=3.6,<3.7.0a0'] -> libgfortran4[version='>=7.5.0']
r-mgcv=1.8_23 -> libgfortran[version='>=3.0.1'] -> libgfortran4[version='>=7.5.0']

Package zlib conflicts for:
python=3.7.1 -> zlib[version='>=1.2.11,<1.3.0a0']
rpy2=2.9.4 -> python[version='>=3.7,<3.8.0a0'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8']
r-mgcv=1.8_23 -> r-base[version='>=3.5.0,<3.5.1.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
r=3.5.1 -> r-base[version='>=3.5.1,<3.5.2.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']

Package r-mgcv conflicts for:
r=3.5.1 -> r-recommended=3.5.1 -> r-mgcv
r-mgcv=1.8_23

Package readline conflicts for:
rpy2=2.9.4 -> readline[version='7.0.*|>=7.0,<8.0a0|>=8.0,<9.0a0']
rpy2=2.9.4 -> r-base[version='>=3.6,<3.7.0a0'] -> readline[version='6.2.*|7.0|>=8.1,<9.0a0|7.*']

What Should I do ?

**Comment by zhangli271828** [comment]
HI,

I have a new problem.
When I ran correct-cnv, I got the following error message from the log
file:

root                      INFO    @ 08/16/21 13:16:17:
# ARGUMENT LIST:
# Cooler URI = inter_30_10k.cool
# CNV Profile = cnv.out
# Number of Processes = 16
# Log file name = cnv-norm2.log
root                      INFO    @ 08/16/21 13:16:18: Match CNV
segmentation to matrix bins
Traceback (most recent call last):
  File
"/usr/local/anaconda3-2020/envs/neoloop/lib/python3.7/site-packages/pandas/core/indexes/base.py",
line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in
pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in
pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in
pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in
pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'weight'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3-2020/envs/neoloop/bin/correct-cnv", line 92,
in run
    bincnv.assign_cnv(args.hic)
  File
"/usr/local/anaconda3-2020/envs/neoloop/lib/python3.7/site-packages/neoloop/cnv/loadcnv.py",
line 87, in assign_cnv
    bias = cooler_lib.bins().fetch(ref_k)['weight'].values
  File
"/usr/local/anaconda3-2020/envs/neoloop/lib/python3.7/site-packages/pandas/core/frame.py",
line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File
"/usr/local/anaconda3-2020/envs/neoloop/lib/python3.7/site-packages/pandas/core/indexes/base.py",
line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'weight'
----------------------------------------------------------------------------------------------------------------------------------

Please help me to fix it.  Thanks!

**Comment by XiaoTaoWang** [comment]
Hi, this is a duplicate issue (issue #8), just make sure you have run "cooler balance" on your cool files before "correct-cnv".

**Comment by zhangli271828** [comment]
HI,
I solved my previous issue. Thanks!
I have a new issue: in multiple samples, I simply got no output from
running assemble-complexSVs.

I put the issue on your git website. Please take a look at it.
Thanks again for your help

Li Zhang
