### ISSUE TITLE
The  discrepancies of neoloop results and neotad results

### ISSUE THREAD

**Issue by wzhang42** [XiaoTaoWang/NeoLoopFinder#17]
Hi, Xiaotao,
    I have compared the results of neoloops and neotads.  I found that neotad report some new thing  which is not in the early step neoloops. I am puzzed. My boss also want me to make an explanation.  I read through your Nature method papers and other related papers and generally conclude as the two points ( I want your confirmation).
1.) neoloops is based a machine learning module, peakachu.
 2.) neotad is not based on machine-learning method , even not based the  neo-loop results, but based on a method for DI based boundary detection  (your 2017 NAR paper).    
Thank you in advance

**Comment by XiaoTaoWang** [comment]
Yes, you're correct, Neo-loops and Neo-tads are detected using different methods, so it's not a surprise to see they are not the same.
