### ISSUE TITLE
input with mouse cells

### ISSUE THREAD

**Issue by skytguuu** [XiaoTaoWang/NeoLoopFinder#19]
Hi,

I was wondering whether this tool worked in mouse or not? It seemed need hic_breakfinder's output file, however, hic_breakfinder only support the expect file in human. 

Could you give me a hand?

Thanks

**Comment by XiaoTaoWang** [comment]
Yes, hic_breakfinder can only detect SVs in human cells; but NeoLoopFinder should work for mouse cells as well once you have an SV list.

**Comment by skytguuu** [comment]
Thanks for your help. Indeed, NeoLoopFinder could work for mouse cells, however it need "K562-test-SVs.txt" file, which I thought came out frome hic_breakfinder output. Am I undersanding right? How can I get the input file of assemble-complexSVs?

Thanks

**Comment by XiaoTaoWang** [comment]
Yes, you are right. I'm sorry but as far as I know, there's no software that can detect SVs from Hi-C map of non-human cells.

**Comment by skytguuu** [comment]
I see, thanks for your explanation.  

Thanks!
