### ISSUE TITLE
neoloop-caller has some error 

### ISSUE THREAD

**Issue by yangfeizZZ** [XiaoTaoWang/NeoLoopFinder#35]
Hi:
when i run neoloop-caller follow your code,some error occur.
The code is :  neoloop-caller -O K562.neo-loops.txt -H K562-MboI-allReps-hg38.10K.cool --assembly K562.assemblies.txt --no-clustering --prob 0.95
The error is:  /home/yangfei/.conda/envs/neoloop/lib/python3.7/site-packages/neoloop/util.py:415: RuntimeWarning: invalid value encountered in greater
I don't know how to solve it.

**Comment by JSegueni** [comment]
Hi,

This seems to be just a warning message not an error message.

Are you sure you pasted the right message?

**Comment by yangfeizZZ** [comment]
> Hi,
> 
> This seems to be just a warning message not an error message.
> 
> Are you sure you pasted the right message?

**Comment by yangfeizZZ** [comment]
> Hi: when i run neoloop-caller follow your code,some error occur. The code is : neoloop-caller -O K562.neo-loops.txt -H K562-MboI-allReps-hg38.10K.cool --assembly K562.assemblies.txt --no-clustering --prob 0.95 The error is: /home/yangfei/.conda/envs/neoloop/lib/python3.7/site-packages/neoloop/util.py:415: RuntimeWarning: invalid value encountered in greater I don't know how to solve it.

**Comment by yangfeizZZ** [comment]
> Hi,
> 
> This seems to be just a warning message not an error message.
> 
> Are you sure you pasted the right message?

It is an error.when i frist run ,the error is:
root                      INFO    @ 09/09/22 17:51:54: 
# ARGUMENT LIST:
# Output Path = M1.neo-loop.txt
# Cache Folder = .cache
# SV assembly = M1.assemblies.txt
# Cooler List = ['M1_5000.cool']
# Extended Genomic Span = 5000000bp
# Balance Type = CNV
# Probability threshold = 0.95
# No pooling = True
# Minimum marginal peaks = 2
# Number of Processes = 1
# Log file name = neoloop.log
--2022-09-09 17:52:01--  https://dl.dropboxusercontent.com/s/mwcdn9j4rjrb5u2/high-confidence.100million.5kb.pkl?dl=0
正在解析主机 dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 199.59.150.49, 2001::a27d:2009
正在连接 dl.dropboxusercontent.com (dl.dropboxusercontent.com)|199.59.150.49|:443... 失败：连接超时。
正在连接 dl.dropboxusercontent.com (dl.dropboxusercontent.com)|2001::a27d:2009|:443... 失败：网络不可达。

when i run again.the error is:
root                      INFO    @ 09/09/22 17:54:26: 
# ARGUMENT LIST:
# Output Path = M1.neo-loop.txt
# Cache Folder = .cache
# SV assembly = M1.assemblies.txt
# Cooler List = ['M1_5000.cool']
# Extended Genomic Span = 5000000bp
# Balance Type = CNV
# Probability threshold = 0.95
# No pooling = True
# Minimum marginal peaks = 2
# Number of Processes = 1
# Log file name = neoloop.log
root                      INFO    @ 09/09/22 17:54:33: Load assembled SVs
root                      INFO    @ 09/09/22 17:54:33: Current resolution: 5000
root                      INFO    @ 09/09/22 17:54:33: Calculate the global average contact frequencies at each genomic distance ...
/home/marh/miniconda3/envs/neoloop/lib/python3.7/site-packages/neoloop/util.py:415: RuntimeWarning: invalid value encountered in greater
  tmp = np.isfinite(weights) & (weights > 0)
root                      INFO    @ 09/09/22 17:57:05: Done
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
