### ISSUE TITLE
What's the best way to generate the simple SV file?

### ISSUE THREAD

**Issue by csijcs** [XiaoTaoWang/NeoLoopFinder#4]
Really happy you generated this useful tool. What is the best method to generate the simple SV file? I made one with hic_breakfinder, but when I use it with assemble-complexSVs is get no connected assemblies and no R^2 or slope values.

Here is the command I ran:
```
assemble-complexSVs -O BC004_BR_sv -B ../hic_breakfinder/BC004_BR.breaks_sv.txt \
-H ../cool_files/BC004_BR_all_reps_40000_cnv_corrected.cool
```

The .cool file was generated initially from Hi-C Pro .allValidPairs file, balanced, then cnv_corrected with `calculate-cnv`, `segment-cnv`, and `correct-cnv`:

```
clr = cooler.Cooler('BC004_BR_all_reps_40000_cnv_corrected.cool')
clr.bins()[:100]
chrom | start | end | CNV | CNVI | sweight | weight
chr1 | 0 | 40000 | 0.0 | 0 | NaN | NaN
chr1 | 40000 | 80000 | 0.0 | 0 | NaN | NaN
chr1 | 80000 | 120000 | 0.0 | 0 | NaN | NaN
chr1 | 120000 | 160000 | 0.0 | 0 | NaN | NaN
chr1 | 160000 | 200000 | 0.0 | 0 | NaN | NaN
... | ... | ... | ... | ... | ... | ...
chr1 | 3800000 | 3840000 | 3.0 | 3 | 0.021814 | 0.020394
chr1 | 3840000 | 3880000 | 3.0 | 3 | 0.022483 | 0.020884
chr1 | 3880000 | 3920000 | 3.0 | 3 | 0.025079 | 0.022933
chr1 | 3920000 | 3960000 | 3.0 | 3 | 0.021267 | 0.019760
chr1 | 3960000 | 4000000 | 3.0 | 3 | 0.019646 | 0.018307
```

The BC004_BR.breaks_sv.txt was generated from hic_breakfinder using a merged bam of the bwt2pairs.bam files from Hi-C Pro, and then awking the appropriate columns to a tab-separated file:
```
$ head ../hic_breakfinder/BC004_BR.breaks_sv.txt
chr1	chr7	+-	45000000	15120000	translocation
chr1	chr7	--	60660000	39780000	translocation
chr1	chr7	+-	113070000	6380000	translocation
chr1	chr22	++	70130000	17060000	translocation
```

Here's the tail of the output from the run:
```
neoloop.callers           INFO    @ 07/07/21 17:10:08: translocation,8,111000000,+,6,163000000,+: left slope: 0, R^2: 0
neoloop.callers           INFO    @ 07/07/21 17:10:08: translocation,8,111000000,+,6,163000000,+: right slope: 0, R^2: 0
neoloop.callers           INFO    @ 07/07/21 17:10:08: translocation,8,111000000,+,6,163000000,+, middle slope: 0, R^2: 0
[Parallel(n_jobs=1)]: Done 199 out of 199 | elapsed:   19.6s finished
root                      INFO    @ 07/07/21 17:10:08: 0 SVs left
root                      INFO    @ 07/07/21 17:10:08: Building SV connecting graph ...
root                      INFO    @ 07/07/21 17:10:08: Discovering and re-ordering complex SVs ...
neoloop.assembly          INFO    @ 07/07/21 17:10:08: Filtering 0 redundant candidates ...
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   0 out of   0 | elapsed:    0.0s finished
root                      INFO    @ 07/07/21 17:10:08: Called 0 connected assemblies
root                      INFO    @ 07/07/21 17:10:08: Output ...
root                      INFO    @ 07/07/21 17:10:08: Done
```

I also tried with the non-cnv-corrected cool file and `--balance-type ICE` and got the same results. Any idea what I am doing wrong?

**Comment by XiaoTaoWang** [comment]
Hi, I think the most possible reason is that the strand information/break coordinates were incorrectly extracted. Can you try this script? https://raw.githubusercontent.com/XiaoTaoWang/NeoLoopFinder/master/scripts/prepare-SV-breakpoints.py

    python prepare-SV-breakpoints.py <hic_breakfinder> <output_file_path>

**Comment by csijcs** [comment]
Thanks for the script, but unfortunately I still get the same result

**Comment by XiaoTaoWang** [comment]
What parameters did you set when you ran assemble-complexSVs? For in situ Hi-C datasets, assemble-complexSVs and neoloop-caller may only be run at 5kb, 10kb, 20kb and 25kb resolutions.

**Comment by csijcs** [comment]
Ah, that's likely the issue. My matrices are at 40kb.

Here is the command I used:
```
assemble-complexSVs -O BC004_BR_sv -B ../hic_breakfinder/BC004_BR.breaks_sv.txt \
-H ../cool_files/BC004_BR_all_reps_40000_cnv_corrected.cool
```

There does not appear to be a resolution parameter, so I suppose then I will have to make new matrices at 25kb. Thanks!

**Comment by XiaoTaoWang** [comment]
Yes, please re-run it at 25kb and let me know if it still fails.

**Comment by csijcs** [comment]
Works perfectly at 25kb. Thanks so much!

**Comment by DittmanC** [comment]
> What parameters did you set when you ran assemble-complexSVs? For in situ Hi-C datasets, assemble-complexSVs and neoloop-caller may only be run at 5kb, 10kb, 20kb and 25kb resolutions.

I have been trying to run at 25kb. it said for calculate-cnv at 25kb,
RRuntimeWarning: Error in smooth.construct.tp.smooth.spec(object, dk$data, dk$knots) : 
  A term has fewer unique covariate combinations than specified maximum degrees of freedom

for 100kb, it works. but I got all zero in assemble-complexSVs...
neoloop.callers           INFO    @ 01/11/22 16:24:48: inversion,9,92210000,-,9,130890000,-, middle slope: 0, R^2: 0
neoloop.callers           INFO    @ 01/11/22 16:24:48: translocation,9,103000000,-,X,150740000,+: left slope: 0, R^2: 0
neoloop.callers           INFO    @ 01/11/22 16:24:48: translocation,9,103000000,-,X,150740000,+: right slope: 0, R^2: 0
neoloop.callers           INFO    @ 01/11/22 16:24:48: translocation,9,103000000,-,X,150740000,+, middle slope: 0, R^2: 0
[Parallel(n_jobs=1)]: Done  58 out of  58 | elapsed:    6.0s finished
root                      INFO    @ 01/11/22 16:24:48: 0 SVs left
root                      INFO    @ 01/11/22 16:24:48: Building SV connecting graph ...
root                      INFO    @ 01/11/22 16:24:48: Discovering and re-ordering complex SVs ...
neoloop.assembly          INFO    @ 01/11/22 16:24:48: Filtering 0 redundant candidates ...
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   0 out of   0 | elapsed:    0.0s finished
root                      INFO    @ 01/11/22 16:24:48: Called 0 connected assemblies
root                      INFO    @ 01/11/22 16:24:48: Output ...
root                      INFO    @ 01/11/22 16:24:48: Done
