### ISSUE TITLE
Invalid interval bounds with chr prefix already

### ISSUE THREAD

**Issue by zzhoujialu** [XiaoTaoWang/NeoLoopFinder#42]
Hi, thank you for developing this amazing tool. I'm trying to run calculate-cnv
on a 50kb cool matrix after running the script of [add_prefix_to_cool.py](https://raw.githubusercontent.com/XiaoTaoWang/NeoLoopFinder/master/scripts/add_prefix_to_cool.py) and I still come across the error exactly like the issue #1.

The following is the ginteractions file transforming from my cool file using hicexplorer.
![截屏2023-02-07 16 17 41](https://user-images.githubusercontent.com/97088260/217189585-cf50b24f-76f4-4377-a60e-954fd386dd16.png)
My command line is: calculate-cnv -H /path/to/my/mcool/file::resolutions/50000 -g hg38  -e HindIII --output file.CNV-profile.bedGraph

Do you have any idea of what could be causing the error?
Looking forward to hearing from you. 
Thanks!

**Comment by XiaoTaoWang** [comment]
Hi, this error may happen if your cool file includes chromosomes other than chr1, chr2, ..., chrX, chrY, and chrM. Can you show me all possible chromosome names in your cool file?

**Comment by zzhoujialu** [comment]
Thank you! 
There are much more chromosomes other than chr1, chr2, ..., chrX, chrY, and chrM in my cool file. I removed them and it works. 
Thank you so much!
