### ISSUE TITLE
Python version in installation commands

### ISSUE THREAD

**Issue by kuba11** [XiaoTaoWang/NeoLoopFinder#44]
Hello,

I had numerous issues when installing the tool, I figured out that python version 3.9 is required to avoid dependency conflicts. Could I ask for this information to be added to the installation commands?

Best wishes,
Kuba

**Comment by XiaoTaoWang** [comment]
Hi Kuba, I slightly changed the installation guide by replacing conda with mamba, and found no conflict problems occurred on my end again. Can you try it and let me know your feedback? Thanks!

**Comment by kuba11** [comment]
Hello,

thank you very much for a quick response. Using mamba to create the environment solved the issue, thanks a lot!

Best wishes,
Kuba
