### ISSUE TITLE
Can we use it with a customized reference genome

### ISSUE THREAD

**Issue by xunchen85** [XiaoTaoWang/NeoLoopFinder#48]
Hi XiaoTao,

I am wondering if I could use NeoLoopFinder with a modified hg38 reference genome containing an additional sequence (like a contig) as a separate chromosome?

Thanks,
Xun

**Comment by XiaoTaoWang** [comment]
Hi Xun,

Currently, the CNV module only supports standard hg38, hg19, mm10, and mm9 genomes. However, you may skip "calculate-cnv", "segment-cnv", and "correct-cnv", and directly run "assemble-complexSVs" and "neoloop-caller" using the ICE-normalized matrix as input, by specifying "--balance-type ICE" when you run these two commands.

Best,
Xiaotao

**Comment by xunchen85** [comment]
Hi Xiaotao,

Sorry, I am new to HIC data analysis. I am wondering if we don't need the CNV normalization on the small contigs I added, can I still use standard hg38 when we ran the CNV module?

One more question, I computed the matrix using tools that generated outputs in .hic format. I haven't checked but does it also support the .hic format? If not, how can I use it? Can I use the converted .mcool file from .hic format? Or do you have suggested tools to format it for the use of NeoloopFinder?

Thanks,
Xun

**Comment by XiaoTaoWang** [comment]
“Sorry, I am new to HIC data analysis. I am wondering if we don't need the CNV normalization on the small contigs I added, can I still use standard hg38 when we ran the CNV module?”

Yes, you can. ``calculate-cnv`` will simply ignore these contigs.

"I haven't checked but does it also support the .hic format?"

No, NeoLoopFinder currently only supports .cool/.mcool format.

"Can I use the converted .mcool file from .hic format?"

Yes, you can convert your .hic file into a .mcool file using hic2cool (https://github.com/4dn-dcic/hic2cool). After that, all you need to do is to add the "chr" prefix to the chromosome names in your .mcool file to make it fully compatible with NeoLoopFinder. You can refer to issue #1 for more details.

**Comment by xunchen85** [comment]
Hi Xiaotao,

Very cool. Thanks so much for your help. 

NeoloopFinder is so powerful and I will definitely use it.

Thanks,
Xun
