### ISSUE TITLE
Log2 Copy Number

### ISSUE THREAD

**Issue by Xieeeee** [XiaoTaoWang/NeoLoopFinder#50]
HI Xiaotao,
Kind of a naive question. I see in the `plot-cnv` function the y axis represents log2 copy number, while in many case it is centered around 0. I wonder whether this is the log2 fold change against `ploidy` (2 as default) or it indicates there is only 1 copy?

Best,
Yang

**Comment by XiaoTaoWang** [comment]
Hi Yang, the y axis here represents log2 copy number ratios, where 0 indicates that the copy number of the corresponding genomic loci is equal to the genome-wide average. So, if a sample's genome has an average of 2 copies, then 0 on the y-axis represents 2 copies; if the average is 3 copies, then 0 on the y-axis represents 3 copies.

**Comment by Xieeeee** [comment]
Thank you so much!
