### ISSUE TITLE
juicer v2 .hic file as the input?

### ISSUE THREAD

**Issue by xunchen85** [XiaoTaoWang/NeoLoopFinder#51]
Hi Xiaotao,

How could I use neoloopfinder with the .hic file in V9 format generated by the latest juicer tool? Apparently hic2cool does not support the conversion of .hic V9 file to mcool/cool.

Thanks,
Xun

**Comment by XiaoTaoWang** [comment]
Hi Xun, can you try my another software HiCLift (https://github.com/XiaoTaoWang/HiCLift)? While it was initially developed for coordinate conversion for chromatin contacts, it can also be used for format conversion by setting the "--in-assembly" and "--out-assembly" parameters to the same value.
