### ISSUE TITLE
ploidy parameters and biological replicates choose for Down Syndrome

### ISSUE THREAD

**Issue by linfanxiao** [XiaoTaoWang/NeoLoopFinder#63]
Dear developers,

 I would like to express my gratitude for providing us with your state-of-the-art tool. However, we now have three biological replicates of HiC data in individuals with Down syndrome. Therefore, I would appreciate your guidance on how to select the appropriate ploidy parameters for our analysis.

Furthermore, I would like to inquire whether it would be more appropriate to combine the three replicates together in order to identify neoloops, or if it would be better to analyze them separately and subsequently determine the consensus neoloops.

Lastly, I would like to know if it would be feasible to employ a method such as DESeq2 to detect differential loops between the two conditions (normal vs. Down syndrome).

Thank you very much for your time and I eagerly await your response!

**Comment by XiaoTaoWang** [comment]
Hi, for the ploidy parameter, it should be set as the average number of chromosome copies in your sample. For Down syndrome, I recommend setting this parameter as 2, as only chromosome 21 has three copies in Down syndrome.

As for whether the three replicates should be combined, my quick answer is yes. In Hi-C, sequencing depths are crucial, unlike 1D genomic signals such as RNA-Seq. However, analyzing them separately definitely helps enhance the specificity of loop detection.

Regarding the DESeq2 question, while I have limited experience applying DESeq2 to detect differential loops, it seems feasible (check out this resource: https://mdozmorov.github.io/HiCcompareWorkshop/articles/hic_tutorial.html). 

Xiaotao

**Comment by linfanxiao** [comment]
Thank you for your prompt and warm response. I truly appreciate it. I now have some ideas for analysis!
