### ISSUE TITLE
cnv-calculate Runtime Error

### ISSUE THREAD

**Issue by wzhang42** [XiaoTaoWang/NeoLoopFinder#7]
Hi, XiaoTao,
   I am now playing with the NeoLoopFinder. I use your provided demo .cool file to cnv-calculate, it's ok. But I use my own .cool file, it always report the following Runtime error.

Traceback (most recent call last):
  File "/home/wzhang/.conda/envs/neoloop/bin/calculate-cnv", line 128, in run
    table = runcnv.signal_from_bigwig(table, gc_fil, name='GC')
  File "/home/wzhang/.conda/envs/neoloop/lib/python3.7/site-packages/neoloop/cnv/runcnv.py", line 50, in signal_from_bigwig
    v = bw.stats(row['chrom'], row['start'], row['end'], type='mean')[0]
RuntimeError: Invalid interval bounds!

 The Command lines for the two case are the following:
   calculate-cnv -g hg38 -H K562-MboI-allReps-hg38.10K.cool --output ./calculate-cnv.txt -e MboI --cachefolder ./neoloopfinder (It's ok)
   calculate-cnv -g hg38 -H hic_SH-SY5Y.inter_10000.cool --output ./calculate-cnv.txt -e MboI --cachefolder ./neoloopfinder (Runtime Error)
Could you please provide me some clues to fix this RuntimeError?    Additionally, I use hicConvertFormat to convert .hic to the cool format. The command is the following:
hicConvertFormat -m ./hic_SH-SY5Y.inter.hic --inputFormat hic -o hic_SH-SY5Y.inter.cool --outputFormat cool --resolution 10000

Look forward to hearing from you
Thank you in advance.

**Comment by XiaoTaoWang** [comment]
Hi, can you check issue #1, and let me know if it works after adding "chr" to your cool files.

**Comment by wzhang42** [comment]
Xiaotao, 
    Thank you so much. It seems work.
